# Generated by Django 4.1.3 on 2023-02-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ips",
            old_name="submitted",
            new_name="date",
        ),
    ]
