# Generated by Django 4.1.3 on 2023-02-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_submitted_ips_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                choices=[
                    ("Frontend", "Frontend"),
                    ("UI", "UI"),
                    ("UX", "UX"),
                    ("Coding", "Coding"),
                    ("Testing", "Testing"),
                    ("Database", "Database"),
                    ("Deployment", "Deployment"),
                ],
                max_length=10,
            ),
        ),
    ]
